source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "7.0"

inhibit_all_warnings!

target 'JCBannerView_Example', :exclusive => true do
  pod "JCBannerView", :path => "../"
end

target 'JCBannerView_Tests', :exclusive => true do
  pod "JCBannerView", :path => "../"

  
end
