source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"

target 'JCBannerView_Example' do
  pod "JCBannerView", :path => "../"
end

target 'JCBannerView_Tests' do
  pod "JCBannerView", :path => "../"
end
