source 'https://github.com/CocoaPods/Specs.git'

target 'JCBannerView_Example', :exclusive => true do
  pod "JCBannerView", :path => "../"
end

target 'JCBannerView_Tests', :exclusive => true do
  pod "JCBannerView", :path => "../"

  
end
